environment:
  nodejs_version: "8.0"
  github_access_token:
    secure: Q1dSVpW+OL+sfW1A64a6ud6itfdNj+RcahLtDK/Ys4z/9CuyQNQQGcSVCgetOOP4

init:
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }

branches:
  only:
    - generate-release-docs

cache:
  - '%temp%\nativelibs'
  - '%USERPROFILE%\.nuget\packages'
  - tools -> build.cake, build.ps1, build.sh
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

image: Visual Studio 2017

install:
  - IF NOT EXIST C:\ProgramData\chocolatey\bin\docfx.exe choco install docfx
  - cinst docfx
  - npm install gh-pages -g

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: if(-not $env:is_not_pr) { return }
  - docfx ./docs/docfx.json
  - ps: gh-pages-clean
  - Ps: gh-pages deploy --message "doc update from CI" --dist "./docs/_site" --repo "https://$env:github_access_token@github.com/ravinderjangra/safe_app_csharp.git" --user "Ravinder Jangra <ravinderjangra@live.com>"